-- 1. Ensure topics are read from beginning
SET 'auto.offset.reset' = 'earliest';

-- 2. Create stream for survey_responses

-- 3. Create stream for survey_respondents

-- 4. Create table for survey_respondents
CREATE TABLE SURVEY_RESPONDENTS
WITH (
    FORMAT = 'JSON_SR'
)
AS
SELECT
    RESPONDENT_ID AS RESPONDENT_ID,
    LATEST_BY_OFFSET(NAME) AS NAME,
    LATEST_BY_OFFSET(GENERATION) AS GENERATION,
    LATEST_BY_OFFSET(SATISFACTION) AS SATISFACTION,
    LATEST_BY_OFFSET(CREATED_AT) AS CREATED_AT
FROM POSTGRES_CDCPUBLICSURVEY_RESPONDENTS
GROUP BY RESPONDENT_ID
;

-- 5. Create stream joining both streams
CREATE STREAM SURVEY_RESPONSES_ENRICHED
WITH (
    KAFKA_TOPIC = 'topic_survey_responses_enriched',
    VALUE_FORMAT = 'JSON_SR',
    KEY_FORMAT = 'JSON_SR',
    PARTITIONS = 1
) AS
SELECT
    S.RESPONDENT_ID AS RESPONDENT_ID,
    S.RESPONSE_ID AS RESPONSE_ID,
    T.NAME AS NAME,
    T.GENERATION AS GENERATION,
    T.SATISFACTION AS SATISFACTION,
    S.QUESTION AS QUESTION,
    S.ANSWER AS ANSWER,
    S.IS_REAL AS IS_REAL,
    S.CREATED_AT AS CREATED_AT
FROM POSTGRES_CDCPUBLICSURVEY_RESPONSES S
INNER JOIN SURVEY_RESPONDENTS T
    ON S.RESPONDENT_ID = T.RESPONDENT_ID
EMIT CHANGES
;

-- 6. Verify streams and table
SHOW STREAMS;

SHOW TABLES;

SELECT *
FROM SURVEY_RESPONSES_ENRICHED
EMIT CHANGES;
