-- 1. Ensure topics are read from beginning
SET 'auto.offset.reset' = 'earliest';

-- 2. Create stream for survey_respondents

-- 3. Create stream for survey_responses

-- 4. Create stream joining both streams
CREATE STREAM SURVEY_RESPONSES_ENRICHED
WITH (
    KAFKA_TOPIC = 'topic_survey_responses_enriched',
    VALUE_FORMAT = 'JSON_SR',
    KEY_FORMAT = 'JSON_SR',
    PARTITIONS = 1
) AS
SELECT
    R.RESPONDENT_ID AS RESPONDENT_ID,
    R.RESPONSE_ID AS RESPONSE_ID,
    T.NAME AS NAME,
    T.GENERATION AS GENERATION,
    T.SATISFACTION AS SATISFACTION,
    R.QUESTION AS QUESTION,
    R.ANSWER AS ANSWER,
    R.IS_REAL AS IS_REAL,
    R.CREATED_AT AS CREATED_AT
FROM POSTGRES_CDCPUBLICSURVEY_RESPONSES R
INNER JOIN POSTGRES_CDCPUBLICSURVEY_RESPONDENTS T WITHIN 10 MINUTES GRACE PERIOD 2 MINUTES
    ON R.RESPONDENT_ID = T.RESPONDENT_ID
EMIT CHANGES
;

-- 5. Verify streams and table
SHOW STREAMS;

SELECT *
FROM SURVEY_RESPONSES_ENRICHED
EMIT CHANGES;