-- Ensure topics are read from beginning
SET 'auto.offset.reset' = 'earliest';

-- Create stream for survey_respondents
CREATE OR REPLACE STREAM SURVEY_RESPONDENTS_STREAM (
    RESPONDENT_ID INTEGER,
    NAME VARCHAR,
    GENERATION VARCHAR,
    CREATED_AT VARCHAR
)
WITH (
    KAFKA_TOPIC = 'postgres_cdc.public.survey_respondents',
    VALUE_FORMAT = 'JSON',
    KEY_FORMAT='NONE'
)
;

-- Create stream for survey_responses
CREATE OR REPLACE STREAM SURVEY_RESPONSES_STREAM (
    RESPONSE_ID INTEGER,
    RESPONDENT_ID INTEGER,
    QUESTION VARCHAR,
    ANSWER VARCHAR,
    IS_REAL BOOLEAN,
    CREATED_AT VARCHAR
)
WITH (
    KAFKA_TOPIC = 'postgres_cdc.public.survey_responses',
    VALUE_FORMAT = 'JSON',
    KEY_FORMAT='NONE'
)
;

-- Create stream joining both streams
CREATE OR REPLACE STREAM SURVEY_RESPONSES_ENRICHED
WITH (
    KAFKA_TOPIC = 'topic_survey_responses_enriched',
    VALUE_FORMAT = 'JSON',
    KEY_FORMAT = 'JSON',
    PARTITIONS = 6
) AS
SELECT
    R.RESPONDENT_ID AS RESPONDENT_ID,
    R.RESPONSE_ID AS RESPONSE_ID,
    T.NAME AS NAME,
    T.GENERATION AS GENERATION,
    R.QUESTION AS QUESTION,
    R.ANSWER AS ANSWER,
    R.IS_REAL AS IS_REAL,
    R.CREATED_AT AS CREATED_AT
FROM SURVEY_RESPONSES_STREAM R
INNER JOIN SURVEY_RESPONDENTS_STREAM T WITHIN 10 MINUTES GRACE PERIOD 2 MINUTES
    ON R.RESPONDENT_ID = T.RESPONDENT_ID
EMIT CHANGES
;

-- Verify streams and table
SHOW STREAMS;

SELECT *
FROM SURVEY_RESPONSES_ENRICHED
EMIT CHANGES;
