--
CREATE TABLE SURVEY_RESPONDENTS (
    RESPONDENT_ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    GENERATION VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP
);

--
CREATE TABLE SURVEY_RESPONSES (
    RESPONSE_ID SERIAL NOT NULL PRIMARY KEY,
    RESPONDENT_ID INT NOT NULL REFERENCES SURVEY_RESPONDENTS(RESPONDENT_ID),
    QUESTION VARCHAR(100) NOT NULL,
    ANSWER VARCHAR(100) NOT NULL,
    IS_REAL BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- JOIN
SELECT
    T2.NAME,
    T2.GENERATION,
    T1.RESPONDENT_ID,
    T1.RESPONSE_ID,
    T1.QUESTION,
    T1.ANSWER,
    T1.CREATED_AT
FROM SURVEY_RESPONSES T1
INNER JOIN SURVEY_RESPONDENTS T2
    ON T1.RESPONDENT_ID = T2.RESPONDENT_ID
WHERE T1.RESPONDENT_ID = 45
;

-- ANALYSIS
SELECT
    T2.GENERATION,
    T1.ANSWER,
    COUNT(*) AS AMOUNT
FROM SURVEY_RESPONSES T1
INNER JOIN SURVEY_RESPONDENTS T2
    ON T1.RESPONDENT_ID = T2.RESPONDENT_ID
WHERE T1.QUESTION = 'When it comes to superheroes:'
GROUP BY 1, 2
ORDER BY 3 DESC
;
